### ISSUE TITLE
Job start and finish Event

### ISSUE THREAD

**Issue by elektryk157** [sjdawson/TruckSimulatorPlugin#1]
Hello.
there is a need for a parameter that would describe that job is in progress, or done

**Comment by sjdawson** [comment]
Hi @elektryk157 

Thanks for suggesting this as a feature - I've updated the plugin to v.1.1.3 now, which includes a new property called `Job.InProgress`. This will tell you whether your're on a job or not. I hope it fits the requirements for your dash. 😃 

Please feel free to reopen this if you have any problems!

**Comment by elektryk157** [comment]
Hi, first I would like to thank you for this feature with job start and finish, it was very helpful for me and I believe other users too. However, there is a problem with ETS 2 version 1.37 and above, because both the Job.in.progress and Job.status parameters do not change, they remain "false" and "none" all the time.
Best regards,
  Bartek

**Comment by sjdawson** [comment]
Hi @elektryk157 

Thanks for reporting this issue.

Could I ask what kind of job you are doing at the time (Quick, Freight or Cargo)?

**Comment by elektryk157** [comment]
Hi, thanks for the fast reply. 
Currently, I could only check it on Quick Job, and Freight, on cargo my game crash for some reason, but as soon as possible, I'll give you an update on how it looks with cargo.

**Comment by sjdawson** [comment]
Can I also ask what version of SimHub you're running? Is it 7.0.7?

**Comment by elektryk157** [comment]
Yes, is 7.0.7

**Comment by sjdawson** [comment]
Could you try the release I've just made? https://github.com/sjdawson/TruckSimulatorPlugin/releases/tag/2.0.1

I **think/hope** that should solve it.

**Comment by elektryk157** [comment]
Now, I tested on 1.38 (currently i run few other game versions) and yes, it solve the problem, but like i said earlier on this version of game i can`t check how it works on cargo, but anyways if I have any problem, I'll let you know. At this moment, massive thanks for all your great work.

**Comment by sjdawson** [comment]
Excellent news!

It should be fine on cargo now as well. 👍🏻

Thanks for the kind words. 😁

**Comment by elektryk157** [comment]
Hi again, i have another issue. When I cancel or finish the job, the Job.in.progress parameter changes to false and Job.status parameter changes to none, thats is correct, but when I take another job, this two parameters stay as they were until I restart simhub.

**Comment by sjdawson** [comment]
Would you be able to send a SimHub recording of the issue if you can recreate it consistently? I can follow through the recording to try and find out where it's getting confused.

Also - there is an action that you can call, `TruckSimulatorPlugin.ResetJobStatus`, which can sometimes sort the status out when it gets confused, which may be useful in the meantime until I can get it debugged properly. :)
