### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Anaouk811** [sjdawson/TruckSimulatorPlugin#6]
The .exe file doesn't Install the plugin and I don't know why

**Comment by Anaouk811** [comment]
Precision: The plugin is installed but he doesn't work

**Comment by sjdawson** [comment]
Hi @Anaouk811, could you tell me which version of SimHub you're running, so that I can investigate.

**Comment by Anaouk811** [comment]
Hello @sjdawson , I run the 7.4.22 version of SimHub. Yes the `sjdawson.TruckSimulatorPlugin.dll` is in my SimHub directory

**Comment by sjdawson** [comment]
> Yes the `sjdawson.TruckSimulatorPlugin.dll` is in my SimHub directory

And when you restarted SimHub, it didn't show a popup asking if you want to enable the plugin? 

If you head to "Settings -> Plugins" in SimHub, does it have the entry in there for Truck Simulator Plugin?

![image](https://user-images.githubusercontent.com/1701603/181261888-b40fd71a-1844-4e47-ac46-7602b3f300c5.png)

**Comment by Anaouk811** [comment]
![image](https://user-images.githubusercontent.com/62028926/181271220-8a8c6de4-9cb9-482b-aac0-f7340c3122e8.png)

**Yes it's enable but when I want to star my dashboard, it shows me this**

![image](https://user-images.githubusercontent.com/62028926/181271460-42da75f7-5998-4b47-bac1-edfae3fae251.png)

**Comment by sjdawson** [comment]
> Yes it's enable but when I want to star my dashboard, it shows me this

Can you send me / link to the dashboard you're trying to run there? I've a feeling it's something to do with setting up that dashboard, as the plugin appears to be installed and working fine.

**Comment by Anaouk811** [comment]
Yep, this is the link : https://www.simhubdash.com/community-2/dashboard-templates/new-ets2-dashboard-for-simhub-v1-0/

**Comment by sjdawson** [comment]
Ah, looks like that message at the bottom isn't telling you it's not installed, moreso just a reminder that you need to install it if you haven't. If you start playing ETS/ATS and it shows connected in SimHub, then the dashboard should change to the main screen:

![image](https://user-images.githubusercontent.com/1701603/181276853-50d52e80-3152-4efe-aaa0-001eacc7c95f.png)

**Comment by Anaouk811** [comment]
Oooooooooh that's why. Also I uptaded my SimHub and all of the dashborad is fonctional. Sorry for the trouble. Thank you for you're help

**Comment by sjdawson** [comment]
> Oooooooooh that's why. Also I uptaded my SimHub and all of the dashborad is fonctional. Sorry for the trouble. Thank you for you're help

You're quite welcome! Happy trucking!

**Comment by NigeUK** [comment]
Hi Steven,
Thanks for your input.
The dashboard in question is mine, and the issue of the missing buttons (on the idle screen) is due to my creating the dashboard using SimHub v8. Earlier versions of SimHub can't run the dashboard.

**Comment by sjdawson** [comment]
Hey @NigeUK,

I was about to post on the dashboard on the SimHub forum about the message at the bottom of your config page in the dash - wonder if it can have a visibility toggle set somehow based on the plugin being available... 🤔

**Comment by NigeUK** [comment]
Yes, I'm thinking the same thing.
My installation instructions need ets2 to be non-running to configure the dash.
I could test for null on one of your properties and then display a 'Trucksim Plugin Not Installed' message if null is true.
Would that work?

**Comment by sjdawson** [comment]
> Would that work?

Yeah, that should work - I'd suggest `TruckSimulatorPlugin.Dashboard.DisplayUnitMetric` as it's initialised to `True` or `False` on load if the plugin is there, it should report `null` if it's not. 👍🏻

**Comment by NigeUK** [comment]
Thanks Steven.
I've added a test for your plugin - confirmation in green if installed, otherwise red warning.
I also added a test for SimHub version - red warning if less than 8.
Thanks again for your input.
